---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jxpipelines.fullname" . }}
  labels: {{- include "jxpipelines.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jxpipelines.fullname" . }}
  labels: {{- include "jxpipelines.labels" . | nindent 4 }}
rules: {{- toYaml .Values.role.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jxpipelines.fullname" . }}
  labels: {{- include "jxpipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jxpipelines.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jxpipelines.fullname" . }}
  namespace: {{ .Release.Namespace }}