apiVersion: v2
description: Jenkins-X Custom charts
name: lighthouse-webui-plugin-proxy
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
version: 0.0.1
appVersion: 0.0.1
